name: Auto Generate Documentation
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches: main
    paths:
      - 'Website/src/content/docs/**/*.mdx'
  pull_request:
    branches: main
    paths:
      - 'Website/src/content/docs/**/*.mdx'
  workflow_dispatch:
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Website/package-lock.json
      - name: Install dependencies
        run: |
          cd Website
          npm install
      - name: Run documentation generation script
        run: |
          cd Website
          npm run generate-docs
      - name: Check for changes
        id: verify-changed-files
        run: |
          if ! git diff --quiet; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Files have been modified:"
            git status
            git diff --name-only
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No files were modified"
          fi
      - name: Commit and push changes directly
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"

          if [ -n "${{ secrets.PAT_TOKEN }}" ]; then
            git remote set-url origin "https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"
          else
            git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          fi

          git add Website/src/content/index.tsx
          git add Website/src/data/searchItems.tsx
          git add Website/package-lock.json

          git commit -m "docs: auto-generate documentation entries

          - Updated component sections in index.tsx
          - Updated search items for new MDX documentation

          Generated by: ${{ github.workflow }} (#${{ github.run_number }})
          Triggered by: ${{ github.actor }}
          Commit SHA: ${{ github.sha }}"

          if git push origin HEAD:main; then
            exit 0
          else
            git push --force-with-lease origin HEAD:main
          fi
      - name: Trigger Vercel Deployment
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_${{ secrets.VERCEL_PROJECT_ID }}/$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
      - name: Create Pull Request (Fallback)
        if: failure() && steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: |
            docs: auto-generate documentation entries

            - Updated component sections in index.tsx
            - Updated search items for new MDX documentation

            Generated by: ${{ github.workflow }} (#${{ github.run_number }})
          title: 'Auto-generated docs update (Fallback)'
          body: |
            ## Automated Documentation Update (Fallback Mode)

            Direct push failed, creating PR instead.

            ### Changes:
            - Updated `Website/src/content/index.tsx`
            - Updated `Website/src/data/searchItems.tsx`

            ### Details:
            - **Triggered by:** ${{ github.event_name == 'push' && 'Push to main' || format('PR #{0}', github.event.number) }}
            - **Workflow:** ${{ github.workflow }}
            - **Run:** #${{ github.run_number }}
          branch: auto-docs-update-${{ github.run_number }}
          delete-branch: true
